# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90f814bb72a1dc5f433f5b297be0f78bfca3e06f8fd68068d99110b47389ee3646fdc9b8891491cfc1e9e33e88802a2bdc3c0f0870d7dc62795647c8f1da28e0

test:
  secret_key_base: 5e615049de686e3d8c33e136a7a775e230579edec094a19e96bad02a913f6032269da73ea98d8334921093b711a72f16d1fbbd2919d458037c5b78b032ebcc04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
